<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="C:\Users\Modern Computer\OneDrive\Desktop\Portfolio\Backend Projects\e-commerce-api\Application\AreaService.cs" Link="AreaService.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.27.8" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.15.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Models\Domain.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />

  </ItemGroup>
  <ItemGroup>
    <None Include="CartService.cs" />
    <None Include="CategoryService.cs" />
    <None Include="OfferService.cs" />
    <None Include="OrderService.cs" />
    <None Include="ProductService.cs" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Features\Account\Interfaces\" />
    <Folder Include="Features\Cart\Interfaces\" />
    <Folder Include="Features\Categories\Interfaces\" />
    <Folder Include="Features\Delivery\Area\Interfaces\" />
    <Folder Include="Features\Delivery\Governorate\Interfaces\" />
    <Folder Include="Features\Messages\Interfaces\" />
    <Folder Include="Features\Notifications\DTOs\" />
    <Folder Include="Features\Notifications\Interfaces\" />
    <Folder Include="Features\Offers\Interfaces\" />
    <Folder Include="Features\Orders\Interfaces\" />
    <Folder Include="Features\Ptoducts\Interfaces\" />
  </ItemGroup>

</Project>
