// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext (typeof(DbContext ))]
    [Migration("20251216225719_CreateGovernoratesAndAreasForDelivery")]
    partial class CreateGovernoratesAndAreasForDelivery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Area", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("governorateId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("governorateId");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("Domain.Cart", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("Domain.CartProduct", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cartId")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("cartId");

                    b.HasIndex("productId");

                    b.ToTable("CartProduct");
                });

            modelBuilder.Entity("Domain.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "المشروبات"
                        },
                        new
                        {
                            id = 2,
                            name = "الأطعمة الأساسية"
                        },
                        new
                        {
                            id = 3,
                            name = "المعلبات واللحوم"
                        });
                });

            modelBuilder.Entity("Domain.Governorate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("deliveryFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Governorate");
                });

            modelBuilder.Entity("Domain.Message", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("Domain.Offer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("discount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Offer");

                    b.HasData(
                        new
                        {
                            id = 1,
                            discount = 10,
                            name = "خصم 10% على المشروبات"
                        });
                });

            modelBuilder.Entity("Domain.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("areaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("delivaryFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("governorateId")
                        .HasColumnType("int");

                    b.Property<bool>("isPaid")
                        .HasColumnType("bit");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("paymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<decimal>("subTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("totalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("trackingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("areaId");

                    b.HasIndex("governorateId");

                    b.HasIndex("userId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Domain.OrderProduct", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("orderId")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("orderId");

                    b.HasIndex("productId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("categoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            id = 1,
                            categoryId = 1,
                            description = "قهوة عربية تقليدية",
                            imageUrl = "https://example.com/images/arabic-coffee.jpg",
                            name = "قهوة عربية",
                            price = 100m,
                            quantity = 0
                        },
                        new
                        {
                            id = 2,
                            categoryId = 1,
                            description = "شاي صحي ومنعش",
                            imageUrl = "https://example.com/images/green-tea.jpg",
                            name = "شاي أخضر",
                            price = 80m,
                            quantity = 0
                        },
                        new
                        {
                            id = 3,
                            categoryId = 1,
                            description = "عصير طبيعي 100%",
                            imageUrl = "https://example.com/images/orange-juice.jpg",
                            name = "عصير برتقال",
                            price = 50m,
                            quantity = 0
                        },
                        new
                        {
                            id = 4,
                            categoryId = 1,
                            description = "قهوة تركية ممتازة",
                            imageUrl = "https://example.com/images/turkish-coffee.jpg",
                            name = "قهوة تركية",
                            price = 120m,
                            quantity = 0
                        },
                        new
                        {
                            id = 5,
                            categoryId = 1,
                            description = "شاي أسود فاخر",
                            imageUrl = "https://example.com/images/black-tea.jpg",
                            name = "شاي أسود",
                            price = 70m,
                            quantity = 0
                        },
                        new
                        {
                            id = 6,
                            categoryId = 1,
                            description = "عصير طبيعي منعش",
                            imageUrl = "https://example.com/images/apple-juice.jpg",
                            name = "عصير تفاح",
                            price = 55m,
                            quantity = 0
                        },
                        new
                        {
                            id = 7,
                            categoryId = 2,
                            description = "جبنة طازجة",
                            imageUrl = "https://example.com/images/white-cheese.jpg",
                            name = "جبنة بيضاء",
                            price = 120m,
                            quantity = 0
                        },
                        new
                        {
                            id = 8,
                            categoryId = 2,
                            description = "بيض طازج يومي",
                            imageUrl = "https://example.com/images/eggs.jpg",
                            name = "بيض طازج",
                            price = 70m,
                            quantity = 0
                        },
                        new
                        {
                            id = 9,
                            categoryId = 2,
                            description = "سكر ناعم",
                            imageUrl = "https://example.com/images/sugar.jpg",
                            name = "سكر أبيض",
                            price = 40m,
                            quantity = 0
                        },
                        new
                        {
                            id = 10,
                            categoryId = 2,
                            description = "زيت ذرة طبيعي",
                            imageUrl = "https://example.com/images/corn-oil.jpg",
                            name = "زيت ذرة",
                            price = 90m,
                            quantity = 0
                        },
                        new
                        {
                            id = 11,
                            categoryId = 2,
                            description = "سمنة بلدي ممتازة",
                            imageUrl = "https://example.com/images/ghee.jpg",
                            name = "سمنة",
                            price = 100m,
                            quantity = 0
                        },
                        new
                        {
                            id = 12,
                            categoryId = 2,
                            description = "لبن طازج",
                            imageUrl = "https://example.com/images/milk.jpg",
                            name = "لبن كامل الدسم",
                            price = 60m,
                            quantity = 0
                        },
                        new
                        {
                            id = 13,
                            categoryId = 3,
                            description = "بسطرمة ممتازة",
                            imageUrl = "https://example.com/images/pastrami.jpg",
                            name = "بسطرمة",
                            price = 200m,
                            quantity = 0
                        },
                        new
                        {
                            id = 14,
                            categoryId = 3,
                            description = "تونة طبيعية",
                            imageUrl = "https://example.com/images/tuna.jpg",
                            name = "تونة معلبة",
                            price = 80m,
                            quantity = 0
                        },
                        new
                        {
                            id = 15,
                            categoryId = 3,
                            description = "فاصوليا طبيعية",
                            imageUrl = "https://example.com/images/beans.jpg",
                            name = "فاصوليا معلبة",
                            price = 50m,
                            quantity = 0
                        },
                        new
                        {
                            id = 16,
                            categoryId = 1,
                            description = "شاي منعش صحي",
                            imageUrl = "https://example.com/images/mint-tea.jpg",
                            name = "شاي أخضر بالنعناع",
                            price = 90m,
                            quantity = 0
                        },
                        new
                        {
                            id = 17,
                            categoryId = 1,
                            description = "قهوة كابتشينو لذيذة",
                            imageUrl = "https://example.com/images/cappuccino.jpg",
                            name = "قهوة كابتشينو",
                            price = 140m,
                            quantity = 0
                        },
                        new
                        {
                            id = 18,
                            categoryId = 1,
                            description = "شاي فاخر برائحة الياسمين",
                            imageUrl = "https://example.com/images/jasmine-tea.jpg",
                            name = "شاي ياسمين",
                            price = 100m,
                            quantity = 0
                        },
                        new
                        {
                            id = 19,
                            categoryId = 1,
                            description = "عصير طبيعي 100%",
                            imageUrl = "https://example.com/images/mango-juice.jpg",
                            name = "عصير مانجو",
                            price = 60m,
                            quantity = 0
                        },
                        new
                        {
                            id = 20,
                            categoryId = 2,
                            description = "جبنة رومي ممتازة",
                            imageUrl = "https://example.com/images/romi-cheese.jpg",
                            name = "جبنة رومي",
                            price = 150m,
                            quantity = 0
                        },
                        new
                        {
                            id = 21,
                            categoryId = 2,
                            description = "بيض طازج للأومليت",
                            imageUrl = "https://example.com/images/omelet-eggs.jpg",
                            name = "بيض أومليت",
                            price = 80m,
                            quantity = 0
                        },
                        new
                        {
                            id = 22,
                            categoryId = 2,
                            description = "سكر بني طبيعي",
                            imageUrl = "https://example.com/images/brown-sugar.jpg",
                            name = "سكر بني",
                            price = 45m,
                            quantity = 0
                        },
                        new
                        {
                            id = 23,
                            categoryId = 2,
                            description = "زيت زيتون ممتاز",
                            imageUrl = "https://example.com/images/olive-oil.jpg",
                            name = "زيت زيتون",
                            price = 150m,
                            quantity = 0
                        },
                        new
                        {
                            id = 24,
                            categoryId = 3,
                            description = "بسطرمة مدخنة فاخرة",
                            imageUrl = "https://example.com/images/smoked-pastrami.jpg",
                            name = "بسطرمة مدخنة",
                            price = 220m,
                            quantity = 0
                        },
                        new
                        {
                            id = 25,
                            categoryId = 3,
                            description = "تونة طبيعية صغيرة",
                            imageUrl = "https://example.com/images/tuna-small.jpg",
                            name = "تونة صغيرة",
                            price = 70m,
                            quantity = 0
                        },
                        new
                        {
                            id = 26,
                            categoryId = 3,
                            description = "فاصوليا طبيعية بيضاء",
                            imageUrl = "https://example.com/images/white-beans.jpg",
                            name = "فاصوليا بيضاء",
                            price = 55m,
                            quantity = 0
                        },
                        new
                        {
                            id = 27,
                            categoryId = 1,
                            description = "عصير طبيعي منعش",
                            imageUrl = "https://example.com/images/pomegranate-juice.jpg",
                            name = "عصير رمان",
                            price = 65m,
                            quantity = 0
                        },
                        new
                        {
                            id = 28,
                            categoryId = 1,
                            description = "قهوة أمريكية خفيفة",
                            imageUrl = "https://example.com/images/american-coffee.jpg",
                            name = "قهوة أمريكية",
                            price = 130m,
                            quantity = 0
                        },
                        new
                        {
                            id = 29,
                            categoryId = 2,
                            description = "لبن زبادي طازج",
                            imageUrl = "https://example.com/images/yogurt.jpg",
                            name = "لبن زبادي",
                            price = 40m,
                            quantity = 0
                        },
                        new
                        {
                            id = 30,
                            categoryId = 2,
                            description = "سمنة بلدي ممتازة",
                            imageUrl = "https://example.com/images/ghee2.jpg",
                            name = "سمنة بلدي",
                            price = 100m,
                            quantity = 0
                        });
                });

            modelBuilder.Entity("Domain.ProductOffer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("applicationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("discountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("offerId")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("offerId");

                    b.HasIndex("productId");

                    b.ToTable("ProductOffer");

                    b.HasData(
                        new
                        {
                            id = 1,
                            applicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            discountValue = 10m,
                            offerId = 1,
                            productId = 1
                        },
                        new
                        {
                            id = 2,
                            applicationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            discountValue = 20m,
                            offerId = 1,
                            productId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Area", b =>
                {
                    b.HasOne("Domain.Governorate", "governorate")
                        .WithMany("areas")
                        .HasForeignKey("governorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("governorate");
                });

            modelBuilder.Entity("Domain.Cart", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Domain.CartProduct", b =>
                {
                    b.HasOne("Domain.Cart", "cart")
                        .WithMany("products")
                        .HasForeignKey("cartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Product", "product")
                        .WithMany("carts")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cart");

                    b.Navigation("product");
                });

            modelBuilder.Entity("Domain.Order", b =>
                {
                    b.HasOne("Domain.Area", "area")
                        .WithMany()
                        .HasForeignKey("areaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Governorate", "governorate")
                        .WithMany()
                        .HasForeignKey("governorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("area");

                    b.Navigation("governorate");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Domain.OrderProduct", b =>
                {
                    b.HasOne("Domain.Order", "order")
                        .WithMany("products")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Product", "product")
                        .WithMany("orders")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.HasOne("Domain.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("Domain.ProductOffer", b =>
                {
                    b.HasOne("Domain.Offer", "offer")
                        .WithMany("products")
                        .HasForeignKey("offerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Product", "product")
                        .WithMany("offers")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("offer");

                    b.Navigation("product");
                });

            modelBuilder.Entity("Domain.Cart", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Domain.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Domain.Governorate", b =>
                {
                    b.Navigation("areas");
                });

            modelBuilder.Entity("Domain.Offer", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Domain.Order", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.Navigation("carts");

                    b.Navigation("offers");

                    b.Navigation("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
